version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
    r-base: "4.1"

sphinx:
   configuration: docs/conf.py

python:
  install:
    - requirements: requirements_docs.txt
    - requirements: requirements.txt
